language: node_js
node_js:
      - "9"
      - "8"
addons:
     firefox: "latest"
before_script:
     - node --version
     - npm --version
install:
     - npm install
script:
      - npm test
after_success: npm run coverage
